<a href="https://colab.research.google.com/github/Abhijithsk/Data_Acquisition_and_ETL_Case-Study/blob/main/casestudy_7_Abhijith.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Task-1

In [16]:
import pandas as pd

In [17]:
df=pd.read_csv('/content/drive/MyDrive/DSAB13/Class_Activity/casestudylibraries/population.csv')
print(df.head(5))
print("\n")

print('Shape : ', df.shape)
print("\n")
print(df.dtypes)

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525


Shape :  (25, 2)


country       object
population     int64
dtype: object

#Task-2

In [18]:
df=pd.read_excel('/content/drive/MyDrive/DSAB13/Class_Activity/casestudylibraries/gdp.xlsx')
print(df)
print('\n')
print(df.dtypes)

           Country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000


Country    object
GDP         int64
dtype: object

#Task-3

In [19]:
df=pd.read_json('/content/drive/MyDrive/DSAB13/Class_Activity/casestudylibraries/internet_users.json')
print(df)

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

#Text-4

In [20]:
df=pd.read_xml('/content/drive/MyDrive/DSAB13/Class_Activity/casestudylibraries/literacy_rate.xml')
df

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

#Task-5

In [21]:
pop=pd.read_csv('/content/drive/MyDrive/DSAB13/Class_Activity/casestudylibraries/population.csv')

gdp=pd.read_excel('/content/drive/MyDrive/DSAB13/Class_Activity/casestudylibraries/gdp.xlsx')

net=pd.read_json('/content/drive/MyDrive/DSAB13/Class_Activity/casestudylibraries/internet_users.json')

lit=pd.read_xml('/content/drive/MyDrive/DSAB13/Class_Activity/casestudylibraries/literacy_rate.xml')

print('Number of rows :',pop.shape[0],'\n Number of columns :', pop.shape[1],
      '\n Column names:', pop.columns, '\n Data types:', pop.dtypes,
      '\n Missing values:', pop.isnull().sum(), '\n Duplicate records:',
      pop.duplicated().sum())
print('\n')
print('Number of rows :',gdp.shape[0],'\n Number of columns :', gdp.shape[1],
      '\n Column names:', gdp.columns, '\n Data types:', gdp.dtypes,
      '\n Missing values:', gdp.isnull().sum(), '\n Duplicate records:',
      gdp.duplicated().sum())
print('\n')

print('Number of rows :',net.shape[0],'\n Number of columns :', net.shape[1],
      '\n Column names:', net.columns, '\n Data types:', net.dtypes,
      '\n Missing values:', net.isnull().sum(), '\n Duplicate records:',
      net.duplicated().sum())
print('\n')

print('Number of rows :',lit.shape[0],'\n Number of columns :', lit.shape[1],
      '\n Column names:', lit.columns, '\n Data types:', lit.dtypes,
      '\n Missing values:', lit.isnull().sum(), '\n Duplicate records:',
      lit.duplicated().sum())

Number of rows : 25
 Number of columns : 2
 Column names: Index(['country', 'population'], dtype='object')
 Data types: country       object
population     int64
dtype: object
 Missing values: country       0
population    0
dtype: int64
 Duplicate records: 0


Number of rows : 25
 Number of columns : 2
 Column names: Index(['Country', 'GDP'], dtype='object')
 Data types: Country    object
GDP         int64
dtype: object
 Missing values: Country    0
GDP        0
dtype: int64
 Duplicate records: 0


Number of rows : 25
 Number of columns : 2
 Column names: Index(['country', 'internet_users'], dtype='object')
 Data types: country           object
internet_users     int64
dtype: object
 Missing values: country           0
internet_users    0
dtype: int64
 Duplicate records: 0


Number of rows : 25
 Number of columns : 2
 Column names: Index(['name', 'literacy_rate'], dtype='object')
 Data types: name              object
literacy_rate    float64
dtype: object
 Missing values: name             0
literacy_rate    0
dtype: int64
 Duplicate records: 0

#Task-6,7,8,9

In [22]:
gdp = gdp.rename(columns={"Country": "country", "GDP": "gdp"})
lit = lit.rename(columns={"name": "country"})
lit["literacy_rate"] = pd.to_numeric(lit["literacy_rate"])

df = pop.merge(gdp, on="country").merge(net, on="country").merge(lit, on="country")

df["internet_penetration"] = (df["internet_users"] / df["population" ] * 100).round(2)
df["gdp_per_capita"] = (df["gdp"] * 1000000 / df["population"]).round(2)
df

,country,population,gdp,internet_users,literacy_rate,internet_penetration,gdp_per_capita
0,United States,331002651,30500000,312000000,99.0,94.26,92144.28
1,China,1411778724,19230000,1080000000,97.2,76.50,13621.11
2,India,1380004385,4187000,850000000,77.7,61.59,3034.05
3,Japan,125836021,4180000,118000000,99.0,93.77,33217.83
4,Germany,83240525,4744000,79000000,99.0,94.91,56991.47
5,United Kingdom,67886011,3839000,66000000,99.0,97.22,56550.68
6,France,65273511,3211000,62000000,99.0,94.98,49193.00
7,Italy,60461826,2420000,56000000,99.0,92.62,40025.25
8,Canada,38005238,2250000,36000000,99.0,94.72,59202.37
9,Australia,25687041,1880000,24000000,99.0,93.43,73188.66
10,Brazil,212559417,2330000,181000000,93.2,85.15,10961.64
11,Russia,145934462,2200000,125000000,99.7,85.65,15075.26
12,South Korea,51780579,1800000,50000000,98.8,96.56,34762.07
13,Spain,46754778,1710000,44000000,98.6,94.11,36573.80
14,Mexico,128932753,1810000,102000000,95.4,79.11,14038.33
15,Indonesia,273523615,1500000,212000000,96.0,77.51,5483.99
16,Saudi Arabia,34813871,1100000,34000000,97.3,97.66,31596.60
17,Turkey,84339067,1350000,69000000,96.7,81.81,16006.82
18,South Africa,59308690,410000,43000000,95.0,72.50,6912.98
19,Argentina,45195774,640000,41000000,99.1,90.72,14160.62
20,Netherlands,17441139,1150000,17000000,99.0,97.47,65936.06
21,Switzerland,8654622,940000,8500000,99.0,98.21,108612.48
22,Sweden,10353442,650000,10100000,99.0,97.55,62781.05
23,Norway,5421241,580000,5300000,100.0,97.76,106986.57
24,Singapore,5850342,530000,5600000,97.5,95.72,90592.99

In [23]:
print(pop.dtypes)
print(gdp.dtypes)
print(net.dtypes)
print(lit.dtypes)

country       object
population     int64
dtype: object
country    object
gdp         int64
dtype: object
country           object
internet_users     int64
dtype: object
country           object
literacy_rate    float64
dtype: object

#Task-10,11

In [24]:
import sqlite3

In [25]:
conn = sqlite3.connect("country.db")
df.to_sql("country_statistics", conn, if_exists="replace", index=False)
print(pd.read_sql("SELECT * FROM country_statistics LIMIT 5", conn))

         country  population       gdp  internet_users  literacy_rate  \
0  United States   331002651  30500000       312000000           99.0
1          China  1411778724  19230000      1080000000           97.2
2          India  1380004385   4187000       850000000           77.7
3          Japan   125836021   4180000       118000000           99.0
4        Germany    83240525   4744000        79000000           99.0

   internet_penetration  gdp_per_capita
0                 94.26        92144.28
1                 76.50        13621.11
2                 61.59         3034.05
3                 93.77        33217.83
4                 94.91        56991.47

#Task-12

In [26]:
print(df.nlargest(5, "gdp")[["country", "gdp"]])
print('\n')

print(df.nlargest(5, "population")[["country", "population"]])
print('\n')

print(df["literacy_rate"].mean())
print('\n')

print(df[df["literacy_rate"] > 90]["country"].tolist())
print('\n')

print(df[df["internet_penetration"] > 70]["country"].tolist())
print('\n')

print(df.nlargest(5, "gdp_per_capita")[["country", "gdp_per_capita"]])
print('\n')

print(df["population"].sum())
print('\n')

print(df["internet_penetration"].mean())
print('\n')

print(df.loc[df["internet_users"].idxmax(), "country"])
print('\n')

print(df["literacy_rate"].corr(df["internet_penetration"]))

         country       gdp
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000


          country  population
1           China  1411778724
2           India  1380004385
0   United States   331002651
15      Indonesia   273523615
10         Brazil   212559417


97.248


['United States', 'China', 'Japan', 'Germany', 'United Kingdom', 'France', 'Italy', 'Canada', 'Australia', 'Brazil', 'Russia', 'South Korea', 'Spain', 'Mexico', 'Indonesia', 'Saudi Arabia', 'Turkey', 'South Africa', 'Argentina', 'Netherlands', 'Switzerland', 'Sweden', 'Norway', 'Singapore']


['United States', 'China', 'Japan', 'Germany', 'United Kingdom', 'France', 'Italy', 'Canada', 'Australia', 'Brazil', 'Russia', 'South Korea', 'Spain', 'Mexico', 'Indonesia', 'Saudi Arabia', 'Turkey', 'South Africa', 'Argentina', 'Netherlands', 'Switzerland', 'Sweden', 'Norway', 'Singapore']


          country  gdp_per_capita
21    Switzerland       108612.48
23         Norway       106986.57
0   United States        92144.28
24      Singapore        90592.99
9       Australia        73188.66


4720039725


89.6596


China


0.77279756813985

#Part F

In [27]:

# 11
print(pd.read_sql("SELECT country, gdp FROM country_statistics ORDER BY gdp DESC LIMIT 5", conn))
print('\n')

# 12
print(pd.read_sql("SELECT ROUND(AVG(literacy_rate), 2) AS avg_literacy FROM country_statistics", conn))
print('\n')

# 13
print(pd.read_sql("SELECT country, literacy_rate FROM country_statistics WHERE literacy_rate > 90", conn))
print('\n')

# 14
print(pd.read_sql("SELECT country, internet_penetration FROM country_statistics ORDER BY internet_penetration DESC LIMIT 5", conn))
print('\n')

# 15
print(pd.read_sql("SELECT SUM(population) AS total_population FROM country_statistics", conn))
print('\n')

# 16
print(pd.read_sql("SELECT country, gdp_per_capita FROM country_statistics ORDER BY gdp_per_capita DESC LIMIT 1", conn))
print('\n')

# 17
pd.read_sql("SELECT * FROM country_statistics", conn).to_csv("country_statistics.csv", index=False)
print('\n')

# 18
print(pd.read_sql("SELECT country, gdp_per_capita FROM country_statistics ORDER BY gdp_per_capita DESC LIMIT 10", conn))

         country       gdp
0  United States  30500000
1          China  19230000
2        Germany   4744000
3          India   4187000
4          Japan   4180000


   avg_literacy
0         97.25


           country  literacy_rate
0    United States           99.0
1            China           97.2
2            Japan           99.0
3          Germany           99.0
4   United Kingdom           99.0
5           France           99.0
6            Italy           99.0
7           Canada           99.0
8        Australia           99.0
9           Brazil           93.2
10          Russia           99.7
11     South Korea           98.8
12           Spain           98.6
13          Mexico           95.4
14       Indonesia           96.0
15    Saudi Arabia           97.3
16          Turkey           96.7
17    South Africa           95.0
18       Argentina           99.1
19     Netherlands           99.0
20     Switzerland           99.0
21          Sweden           99.0
22          Norway          100.0
23       Singapore           97.5


        country  internet_penetration
0   Switzerland                 98.21
1        Norway                 97.76
2  Saudi Arabia                 97.66
3        Sweden                 97.55
4   Netherlands                 97.47


   total_population
0        4720039725


       country  gdp_per_capita
0  Switzerland       108612.48




          country  gdp_per_capita
0     Switzerland       108612.48
1          Norway       106986.57
2   United States        92144.28
3       Singapore        90592.99
4       Australia        73188.66
5     Netherlands        65936.06
6          Sweden        62781.05
7          Canada        59202.37
8         Germany        56991.47
9  United Kingdom        56550.68

In [28]:
conn.close()